2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_setup.py:_flush():71] setting env: {}
2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_init.py:_log_setup():357] Logging user logs to /home/siddhi/workspace/ColorCapsNet/wandb/offline-run-20211028_213217-r7xcsimw/logs/debug.log
2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_init.py:_log_setup():358] Logging internal logs to /home/siddhi/workspace/ColorCapsNet/wandb/offline-run-20211028_213217-r7xcsimw/logs/debug-internal.log
2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_init.py:init():390] calling init triggers
2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-28 21:32:17,044 INFO    MainThread:20596 [wandb_init.py:init():435] starting backend
2021-10-28 21:32:17,044 INFO    MainThread:20596 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-28 21:32:17,050 INFO    MainThread:20596 [backend.py:ensure_launched():198] starting backend process...
2021-10-28 21:32:17,055 INFO    MainThread:20596 [backend.py:ensure_launched():203] started backend process with pid: 20623
2021-10-28 21:32:17,055 INFO    MainThread:20596 [wandb_init.py:init():444] backend started and connected
2021-10-28 21:32:17,056 INFO    MainThread:20596 [wandb_init.py:init():503] updated telemetry
2021-10-28 21:32:17,064 INFO    MainThread:20596 [wandb_init.py:init():576] starting run threads in backend
2021-10-28 21:32:20,645 INFO    MainThread:20596 [wandb_run.py:_console_start():1693] atexit reg
2021-10-28 21:32:20,645 INFO    MainThread:20596 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2021-10-28 21:32:20,646 INFO    MainThread:20596 [wandb_run.py:_redirect():1572] Redirecting console.
2021-10-28 21:32:20,647 INFO    MainThread:20596 [wandb_run.py:_redirect():1628] Redirects installed.
2021-10-28 21:32:20,647 INFO    MainThread:20596 [wandb_init.py:init():603] run started, returning control to user process
2021-10-28 21:32:24,545 INFO    MainThread:20596 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2021-10-28 21:32:24,545 INFO    MainThread:20596 [wandb_run.py:_restore():1635] restore
2021-10-28 21:32:26,933 INFO    MainThread:20596 [wandb_run.py:_wait_for_finish():1793] got exit ret: 
2021-10-28 21:32:27,035 INFO    MainThread:20596 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
local_info {
}

